name: Build and Deploy CI
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'workflow_dispatch') || (contains(github.event.head_commit.message, 'chore(release)')) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/fermium"
          cache: "yarn"
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_GOOGLE_PRIVATE_KEY: ${{secrets.GOOGLE_PRIVATE_KEY}}
          envkey_GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL}}
          envkey_NODEJS_HELPERS: 0
          directory: "./"
          file_name: ".env"
      - run: yarn install
      - run: yarn build
      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
