name: Release CI
on:
  workflow_dispatch:
    branches: [master]
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'workflow_dispatch') }}
    steps:
      - uses: actions/checkout@v2
      - name: Standard Version
      - uses: qzb/standard-version-action@v1.0.5
